### ISSUE TITLE
Target json - please add author, link to repo

### ISSUE THREAD

**Issue by 0xc0170** [rosterloh/target-st-stm32f411re-nucleo#1]
I assume this is the repository for http://yotta.mbed.com/#/target/stm32f411re-nucleo-gcc/0.1.1.

Please update json file with more info. You might want to update the info in the json target file, otherwise it looks the same as F401 which is maintained by ST ("official").

**Comment by rosterloh** [comment]
Done. I've tried many times to submit PRs to have this included but am always fobbed off.
